AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to automate IAM setup for Partner (DLT) Master Account

Resources:

  AllowAllBillingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AllowAllBillingPolicy
      Description: Allow all billing actions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: 
          - aws-portal:*
          Resource: "*"

  DenyOrgUpdatesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DenyOrgUpdatesPolicy
      Description: Deny org create and update actions
      PolicyDocument: { "Version": "2012-10-17",
                        "Statement": [
                          {
                            "Effect": "Deny",
                            "Action": [
                              "organizations:InviteAccountToOrganization",
                              "organizations:DeclineHandshake",
                              "organizations:DetachPolicy",
                              "organizations:DeletePolicy",
                              "organizations:DeleteOrganizationalUnit",
                              "organizations:DisablePolicyType",
                              "organizations:AcceptHandshake",
                              "organizations:CancelHandshake",
                              "organizations:RemoveAccountFromOrganization",
                              "organizations:UpdateOrganizationalUnit",
                              "organizations:UpdatePolicy",
                              "organizations:EnablePolicyType",
                              "organizations:AttachPolicy",
                              "organizations:CreateOrganizationalUnit",
                              "organizations:MoveAccount"
                            ],
                            "Resource": [
                              "arn:aws:organizations::*:handshake/o-*/*/h-*",
                              "arn:aws:organizations::*:policy/o-*/*/p-*",
                              "arn:aws:organizations::*:account/o-*/*",
                              "arn:aws:organizations::*:root/o-*/r-*",
                              "arn:aws:organizations::*:ou/o-*/ou-*"
                            ]
                          },
                          {
                            "Effect": "Deny",
                            "Action": [
                              "organizations:LeaveOrganization",
                              "organizations:EnableAWSServiceAccess",
                              "organizations:DisableAWSServiceAccess",
                              "organizations:EnableAllFeatures",
                              "organizations:CreateAccount",
                              "organizations:DeleteOrganization",
                              "organizations:CreateOrganization",
                              "organizations:CreatePolicy"
                            ],
                            "Resource": "*"
                          }
                        ]
                      }

  DenyScpDetachPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DenyScpDetachPolicy
      Description: Deny detaching of SCPs
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Deny
          Action:
          - organizations:DetachPolicy
          Resource:
          - arn:aws:organizations::166631568452:policy/o-idxghyb7pw/service_control_policy/p-nqtkz47h

  DenyAllBillingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DenyAllBillingPolicy
      Description: Deny all billing actions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Deny
          Action:
          - aws-portal:*
          - ce:*      
          Resource: "*"

  DenyIamUpdatesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DenyIamUpdatesPolicy
      Description: Deny IAM create and update actions
      PolicyDocument: { "Version": "2012-10-17",
                        "Statement": [
                          {
                            "Effect": "Deny",
                            "Action": [
                              "iam:UpdateAssumeRolePolicy",
                              "iam:PutRolePermissionsBoundary",
                              "iam:DeletePolicy",
                              "iam:AttachRolePolicy",
                              "iam:PutRolePolicy",
                              "iam:DeleteRolePermissionsBoundary",
                              "iam:CreateUser",
                              "iam:RemoveUserFromGroup",
                              "iam:DetachRolePolicy",
                              "iam:DeleteRolePolicy",
                              "iam:DetachGroupPolicy",
                              "iam:DetachUserPolicy",
                              "iam:CreatePolicyVersion",
                              "iam:PutGroupPolicy",
                              "iam:CreateGroup",
                              "iam:PutUserPermissionsBoundary",
                              "iam:DeleteUserPolicy",
                              "iam:AttachUserPolicy",
                              "iam:DeleteUserPermissionsBoundary",
                              "iam:CreatePolicy",
                              "iam:AttachGroupPolicy",
                              "iam:PutUserPolicy",
                              "iam:DeleteGroupPolicy",
                              "iam:DeletePolicyVersion",
                              "iam:SetDefaultPolicyVersion"
                            ],
                            "Resource": "*"
                          },
                          {
                            "Effect": "Deny",
                            "Action": "iam:DeleteAccountPasswordPolicy",
                            "Resource": "*"
                          }
                        ]
                      }
Outputs:
  AllowAllBillingPolicy:
    Description: Allow all billing policy
    Value: !Ref AllowAllBillingPolicy
    Export:   # exporting this value so it can be shared
      Name: !Sub '${AWS::StackName}-AllowAllBillingPolicy'

  DenyOrgUpdatesPolicy:
    Description: Deny org updates policy
    Value: !Ref DenyOrgUpdatesPolicy
    Export:   # exporting this value so it can be shared
      Name: !Sub '${AWS::StackName}-DenyOrgUpdatesPolicy'

  DenyScpDetachPolicy:
    Description: Deny detach of SCP policy
    Value: !Ref DenyScpDetachPolicy
    Export:   # exporting this value so it can be shared
      Name: !Sub '${AWS::StackName}-DenyScpDetachPolicy'

  DenyAllBillingPolicy:
    Description: Deny all policy
    Value: !Ref DenyAllBillingPolicy
    Export:   # exporting this value so it can be shared
      Name: !Sub '${AWS::StackName}-DenyAllBillingPolicy'

  DenyIamUpdatesPolicy:
    Description: Deny IAM updates policy
    Value: !Ref DenyIamUpdatesPolicy
    Export:   # exporting this value so it can be shared
      Name: !Sub '${AWS::StackName}-DenyIamUpdatesPolicy'